### ISSUE TITLE
Add Algos & DS implementations repos

### ISSUE THREAD

**Issue by aalhour** [andreis/interview#22]
Hi,

Are you interested in adding links to repositories that implement data structures and algorithms?
I have written a repo in C# when I started studying for interviews and now I maintain it as a research side-project.

Link: [C# ALGORITHMS](https://github.com/aalhour/c-sharp-algorithms)

**Comment by andreis** [comment]
https://github.com/andreis/interview/commit/6a065e8a360d423623bec1d81f1bc653646fd157
