### ISSUE TITLE
Grokit URL is broken

### ISSUE THREAD

**Issue by pranaypareek** [andreis/interview#50]
The URL for the first bullet point in the Questions section titled `Computer Science Primer / Interview Questions` is broken. Screenshot below:

<img width="760" alt="screen shot 2016-11-12 at 12 13 03 am" src="https://cloud.githubusercontent.com/assets/6316230/20235860/5cc86ca2-a86d-11e6-8710-8dc3f7ccfaa7.png">

This can be solved by updating the URL to the current location of the interview questions on the same website which is `http://www.grokit.ca/tag/Computer%20Science%20Interview%20Question/`.

Sending a PR right away.

**Comment by andreis** [comment]
Grokit have a changed URL but I decided to remove them as it doesn't provide a lot of value to my list
