### ISSUE TITLE
Grokking the System Design Interview

### ISSUE THREAD

**Issue by vivekimsit** [andreis/interview#57]
Paid but looks good to me.

https://www.educative.io/collection/5668639101419520/5649050225344512

**Comment by andreis** [comment]
Added in latest

**Comment by birengoyal** [comment]
does anyone has paid account details? it's too expensive. Any hack for it?

**Comment by andreis** [comment]
I doubt any paying user would want to share their login details, sorry. IMHO it's worth investing some money in getting your dream job, but I understand that's not always possible.

**Comment by shashi12533** [comment]
hi i have paid account will share for 75% of purchasing cost
