### ISSUE TITLE
More links

### ISSUE THREAD

**Issue by stereobooster** [andreis/interview#73]
Awesome collection.

Some links which will help to look at the problem in different angle:

- https://www.keyvalues.io/
- https://www.youtube.com/watch?v=yIPbE7BssOs

Bad interview experience:
- http://shivankaul.com/blog/2016/12/07/clean-your-desk-yet-another-amazon-interview-experience.html
- http://seldo.com/weblog/2014/08/26/you_suck_at_technical_interviews
- http://www.gwan.com/blog/20160405.html

Shameless plug, my post on the subject: http://stereobooster.github.io/it-career

**Comment by andreis** [comment]
Damn that's good. I'm hyper mega friggin busy right now, could you make a PR? Thanks!

**Comment by tbatsenko** [comment]
@andreis I've added those links here in a PR 
I was happy to help :) 

Thanks for great resources!
